# After changing this file, check it on:
#   http://lint.travis-ci.org/
language: python
group: travis_latest
os: linux
dist: xenial

# Travis whitelists the installable packages, additions can be requested
#   https://github.com/travis-ci/apt-package-whitelist
addons:
  apt:
    packages: &common_packages
      # Speedup builds
      - eatmydata

cache:
  directories:
    - $HOME/.cache/pip

env:
  global:
    - WITH_CYTHON="true"

stages:
    # Do the style check and a single test job, don't proceed if it fails
    - name: Initial tests
    # Do the rest of the tests
    - name: Comprehensive tests

jobs:
  include:
    # Do all python versions without environment variables set
    - stage: Initial tests
      python: 3.6
    - stage: Comprehensive tests
    - python: 3.8
      env: USE_SDIST=true WITH_COVERAGE=true
    - python: 2.7
  allow_failures:
    - python: 2.7
   

before_install:
  - bash ./build_tools/travis_before_install.sh


script:
  - bash ./build_tools/travis_test.sh

# after_success:
#   - bash ./build_tools/travis-upload-wheel.sh



